# my.env: environment variables every shell gets, AI agents included.
# Rendered into ~/.config/zsh/env.zsh, which .zshenv sources before the
# is_human branch. Only plain variables, so nothing interactive can reach
# agents; PATH stays hand-written in .zshenv because its order is global.
{ config, lib, ... }:
{
  options.my.env = lib.mkOption {
    type = lib.types.attrsOf lib.types.str;
    default = { };
    description = "Variables exported in every zsh, agents included. Values are literal.";
  };

  config.xdg.configFile."zsh/env.zsh".text = lib.concatLines (
    [ "# Generated by nix/home/env.nix. Do not edit." ]
    ++ lib.mapAttrsToList (k: v: "export ${k}=${lib.escapeShellArg v}") config.my.env
  );
}
