# my.human: shell UX for humans only (aliases, plugins, env, snippets).
# Rendered into ~/.config/zsh/human.zsh, which .zshrc sources after the
# `is_human || return 0` guard, so AI agents never see any of it.
{ config, lib, ... }:
let
  inherit (lib) mkOption types;
  cfg = config.my.human;
  sh = lib.escapeShellArg;
in
{
  options.my.human = {
    env = mkOption {
      type = types.attrsOf types.str;
      default = { };
      description = "Environment variables exported for humans.";
    };
    aliases = mkOption {
      type = types.attrsOf types.str;
      default = { };
    };
    globalAliases = mkOption {
      type = types.attrsOf types.str;
      default = { };
    };
    plugins = mkOption {
      default = { };
      description = "zsh plugins to source, keyed by name.";
      type = types.attrsOf (
        types.submodule {
          options = {
            src = mkOption { type = types.path; };
            file = mkOption {
              type = types.str;
              description = "Path of the file to source, relative to src.";
            };
            order = mkOption {
              type = types.int;
              default = 1000;
              description = "Lower is sourced earlier.";
            };
          };
        }
      );
    };
    init = mkOption {
      type = types.lines;
      default = "";
      description = "Free-form zsh (functions, zstyle, bindkey), after plugins and aliases.";
    };
  };

  config.xdg.configFile."zsh/human.zsh".text = lib.concatLines (
    [ "# Generated by nix/home/human.nix. Do not edit." ]
    ++ lib.mapAttrsToList (k: v: "export ${k}=${sh v}") cfg.env
    ++ map (p: "source ${p.src}/${p.file}") (lib.sortOn (p: p.order) (lib.attrValues cfg.plugins))
    ++ lib.mapAttrsToList (k: v: "alias ${k}=${sh v}") cfg.aliases
    ++ lib.mapAttrsToList (k: v: "alias -g ${k}=${sh v}") cfg.globalAliases
    ++ [ cfg.init ]
  );
}
