# my.human: shell UX for humans only (aliases, plugins, env, snippets).
# Rendered into ~/.config/zsh/human.zsh, which .zshrc sources after the
# `is_human || return 0` guard, so AI agents never see any of it.
{ config, lib, ... }:
let
  inherit (lib) mkOption types;
  cfg = config.my.human;
  sh = lib.escapeShellArg;
in
{
  options.my.human = {
    env = mkOption {
      type = types.attrsOf types.str;
      default = { };
      description = "Environment variables exported for humans.";
    };
    aliases = mkOption {
      type = types.attrsOf types.str;
      default = { };
    };
    globalAliases = mkOption {
      type = types.attrsOf types.str;
      default = { };
    };
    plugins = mkOption {
      default = { };
      description = "zsh plugins to source, keyed by name.";
      type = types.attrsOf (
        types.submodule {
          options = {
            src = mkOption {
              type = types.nullOr types.path;
              default = null;
              description = "Plugin root. null for an init-only entry.";
            };
            file = mkOption {
              type = types.str;
              default = "";
              description = "Path of the file to source, relative to src.";
            };
            preInit = mkOption {
              type = types.lines;
              default = "";
              description = "zsh run before sourcing (e.g. zstyle the plugin reads at load time).";
            };
            init = mkOption {
              type = types.lines;
              default = "";
              description = "zsh run right after sourcing.";
            };
            order = mkOption {
              type = types.int;
              default = 1000;
              description = "Lower is sourced earlier. Hand-written ~/.zsh/*.zsh load at 5000.";
            };
          };
        }
      );
    };
    init = mkOption {
      type = types.lines;
      default = "";
      description = "Free-form zsh (functions, zstyle, bindkey), after plugins and aliases.";
    };
  };

  config = {
    # Hand-written zsh (bindkeys, setopts, zstyles...) stays editable in the
    # repo; it must load after plugins that bind keys before `bindkey -v`
    # and before zsh-abbr, which binds space in the resulting keymap.
    my.human.plugins.zsh-local = {
      order = 5000;
      init = ''
        for f in ~/.zsh/[0-9]*.zsh(N); do source "$f"; done
        unset f
      '';
    };

    xdg.configFile."zsh/human.zsh".text = lib.concatLines (
      [ "# Generated by nix/home/human.nix. Do not edit." ]
      ++ lib.mapAttrsToList (k: v: "export ${k}=${sh v}") cfg.env
      ++ lib.concatMap (
        p:
        [ p.preInit ]
        ++ lib.optional (p.src != null) "source ${p.src}/${p.file}"
        ++ [ p.init ]
      ) (lib.sortOn (p: p.order) (lib.attrValues cfg.plugins))
      ++ lib.mapAttrsToList (k: v: "alias ${k}=${sh v}") cfg.aliases
      ++ lib.mapAttrsToList (k: v: "alias -g ${k}=${sh v}") cfg.globalAliases
      ++ [ cfg.init ]
    );
  };
}
