vim.opt.encoding          = "UTF-8"
vim.opt.cursorline        = true
vim.opt.showmode          = true
vim.opt.hidden            = true
vim.opt.confirm           = true
vim.opt.backup            = false
vim.opt.swapfile          = false
vim.opt.undofile          = true
vim.opt.splitright        = true
vim.opt.splitbelow        = true
vim.opt.incsearch         = true
vim.opt.hlsearch          = true
vim.opt.smartcase         = true
vim.opt.ignorecase        = true
vim.opt.autoindent        = true
vim.opt.smartindent       = true
vim.opt.showmatch         = true
vim.opt.laststatus        = 3
vim.opt.scrolloff         = 8
vim.opt.errorbells        = false
vim.opt.pastetoggle       = "<C-\\>"
vim.opt.completeopt       = "menu,menuone,noselect"
vim.opt.shiftwidth  = 0
vim.opt.softtabstop = 2
vim.opt.tabstop     = 2
vim.opt.expandtab   = true
vim.opt.completeopt    = "menu,menuone,noselect"

vim.opt.number         = true
vim.opt.relativenumber = true
-- vim.opt.colorcolumn    = "80"
vim.opt.list           = true
vim.opt.listchars      = { tab = ">..", trail = "·", precedes = "←", extends = "→", eol = "↲", nbsp = "␣" }
vim.opt.termguicolors  = true
