#!/bin/bash

# check arguments
while (( $# > 0 )); do
    case "$1" in
        -h|--help)
            cat <<HELP
Usage: marine [OPTIONS]
  marine shows you many log files effectively

Options:
  -h, --help    show this help
  -l, --locate  specify location (ika:default, fukushima, kamiiso)
  -p, --path    specify full path
HELP
            exit
            ;;
        -a|--all)
            opt_a=true
            ;;
        -d|--date)
            date="$2"; shift
            ;;
        -l|--locate)
            locate="$2"; shift
            ;;
        -p|--path)
            path="$2"; shift
            ;;
    esac
    shift
done

# set path as default
: ${path:=$HOME/data/${locate:=ika}/${date:=$(date +%Y/%m/%d)}}
if [ ! -d "$path" ]; then
    echo "$path: no such file or directory" >&2
    exit 1
fi

if [[ $opt_a == true ]]; then
    res="$(command ls -l "$path" \
        | grep -v "^total"
    )"
    for i in $(awk '{print $9}' <<<"$res")
    do
        echo "$path/$i"
    done
    exit
fi

# fuzzy selection
while out=$(
    command ls -l "$path" \
        | grep -v "^total" \
        | perl -pe 's/^(.* )(.[^ ]*\.txt)$/$1\033[35m$2\033[m/' \
        | awk '{sub($5, "\033[33m"$5"\033[m"); print}' \
        | fzf --ansi --multi --no-sort --tac --query="$q" \
        --print-query --expect=ctrl-v --exit-0); do
    q="$(head -1 <<< "$out")"
    k="$(head -2 <<< "$out" | tail -1)"
    res="$(sed '1,2d;s/^[^a-z0-9]*//;/^$/d' <<< "$out")"
    [ -z "$res" ] && exit #continue
    if [ "$k" = "ctrl-v" ]; then
        LESS='-R -f -i -P ?f%f:(stdin). ?lb%lb?L/%L.. [?eEOF:?pb%pb\%..]'
        LESSOPEN= less +G "$path"/$(awk '{print $9}' <<<"$res")
    else
        for i in $(awk '{print $9}' <<<"$res")
        do
            echo "$path/$i"
        done
        exit
    fi
done
