#!/bin/bash
# vim: ft=sh

trap 'echo Error: $0: stopped' ERR
set -u
set -e

if ! type brew >/dev/null 2>&1; then
    echo 'Requirement: brew' 1>&2
    exit 1
fi

echo 'brew updating...'

brew update
outdated=$(brew outdated)

if [ -n "$outdated" ]; then
    echo 'The following package(s) will upgrade.'
    echo ''
    echo "$outdated"
    echo 'Are you sure?'
    echo 'If you do not want to upgrade, please type Ctrl-c now.'
    echo ''

    # Wait Ctrl-c
    read dummy

    brew upgrade
fi

declare -a BREW_PACKAGES=(
  "ack"
  "autoconf"
  "bdw-gc"
  "caskroom/cask/brew-cask"
  "cmigemo"
  "cowsay"
  "cscope"
  "figlet"
  "freetype"
  "ghostscript"
  "git"
  "go"
  "groff"
  "hub"
  "imagemagick"
  "jbig2dec"
  "jpeg"
  "libevent"
  "libpng"
  "libtiff"
  "libtool"
  "little-cms2"
  "mecab"
  "mecab-ipadic"
  "openssl"
  "pcre"
  "peco/peco/peco"
  "pkg-config"
  "rbenv"
  "reattach-to-user-namespace"
  "ruby-build"
  "shellcheck"
  "terminal-notifier"
  "the_silver_searcher"
  "tig"
  "tmux"
  "tree"
  "vim"
  "w3m"
  "wdiff"
  "wget"
  "xz"
)

for package in "${BREW_PACKAGES[@]}"
do
    if brew list -1 | grep -q "^$(basename $package)"; then
        echo "Skip: brew install ${package}"
    else
        brew install $package
    fi
done
