local:
- name: zsh
  description: My zsh scripts
  directory: ~/.zsh
  plugin:
    if: |
      [[ $SHELL == *zsh* ]]
    sources:
    - '[0-9]*.zsh'
  depends-on:
  - zdharma-continuum/history-search-multi-word
