.TH "GG" "1" "Nov 10, 2014" "favdir.sh user manual" ""
.SH NAME
.PP
reg \- favdir components; Go to favorite directory in \fIfavdirlist\fR
.SH SYNOPSIS
.PP
gg [-h] \fItarget\fR
.SH DESCRIPTION
.PP
Go to the registered path just like jumping.
.PP
On GitHub: <http://github.com/b4b4r07/favdir>
.PP
.SH OPTIONS
Here is a summary of all the options. The following options are available:
.TP 5
.BI -h\fR,\ \fB--help
Print (on the standard output) a description of the command line options understood by gg.
.SH SEE ALSO
.PP
.BR reg (1)
,
.BR del (1)
,
.BR p (1)
,
.BR show (1)
.SH AUTHORS
B4B4R07 <b4b4r07@gmail.com>.
