.TH RICHPAGER 1
.SH NAME
.PP
richpager \- Rich pager; Cat or less automatically, with pygmentize.
.SH SYNOPSIS
.PP
richpager [-h][-lnp][-s \f[I]style\f[]] \f[I]file\f[] \f[I]...\f[]
.SH DESCRIPTION
.PP
This command computes the number of commands you type in 24 hours.
Without any argument, show the number of commands of today.
Otherwise, view retroactively numbers shown in the first argument.
.PP
On GitHub: <http://github.com/b4b4r07/dotfiles/bin/richpager>
.PP
.SH OPTIONS
Here is a summary of all the options. The following options are available:
.TP 12
.BI -h
Display help and exit.
.TP
.BI -l
Forcely, use less as pager nevertheless linage
.TP
.BI -n
Number the output lines, starting at 1
.TP
.BI -p
Use plain text (namely, disuse pygmentize)
.TP
.BI -s\ \f[I]style\f[]
Specify the \f[I]style\f[] of pygments for syntax highlighting
.SH SEE ALSO
.PP
http://pygments.org
.SH LICENSE AND COPYRIGHT
MIT License
.SH AUTHORS
B4B4R07 <b4b4r07@gmail.com>.
