#!/bin/bash
#
# @(#) backup_dotfiles ver.0.1 2014.10.2
#
# Usage:
#   backup_dotfiles [path]
#
# Description:
#   Backup dotfiles directory.
#
######################################################################

function make_tarball()
{
	readonly DOTFILES_ROOT_DIR=~/Dropbox/etc
	readonly TARBALL_FILE_NAME=dotfiles.tar.gz
	cd "$DOTFILES_ROOT_DIR"
	tar cfz "$TARBALL_FILE_NAME" --exclude ".git" dotfiles
	cd "$OLDPWD"
	mv -f "$DOTFILES_ROOT_DIR/$TARBALL_FILE_NAME" "${1:-.}"

	return 0
}

make_tarball "$@"
