#
# First: 
#
update
upgrade

# For groff
brew tap homebrew/dupes

#
# Brew <http://brew.sh/>
#
install ack
install bash
install bash-completion
install colordiff
install coreutils
install cowsay
install findutils
install fortune
install gawk
install gist
install git
install gnu-sed --default-names
install go --cross-compile-common
install groff
install hg
install hub
install macvim --with-lua --with-luajit
install openssl
install tig
install reattach-to-user-namespace
install tmux
install tree
install vim --override-system-vi
install wget

#
# Cask <http://caskroom.io/>
#
brew install caskroom/cask/brew-cask

cask install alfred              || true
cask alfred  link               
cask install appcleaner          || true
cask install bettertouchtool     || true
cask install burn                || true
cask install diskwave            || true
cask install dropbox             || true
cask install evernote            || true
cask install github              || true
cask install google-chrome       || true
cask install google-drive        || true
cask install google-japanese-ime || true
cask install iterm2              || true
cask install keepassx            || true
cask install keyremap4macbook    || true
cask install keyremap4macbook    || true
cask install kobito              || true
cask install lyrics-master       || true
cask install marked              || true
cask install mou                 || true
cask install onepassword         || true
cask install skype               || true
cask install the-unarchiver      || true
cask install vlc                 || true
cask install vox-preference-pane || true
cask install yorufukurou         || true
cask install xtrafinder          || true
# QuickLook plugins
cask install qlcolorcode
cask install qlmarkdown
cask install qlstephen
cask install quicklook-csv 
cask install qlimagesize
cask install scriptql

#
# Final: Remove outdated versions from the cellar
#
cleanup
