# my.ai: shell settings for AI agents only, the counterpart of my.human.
# Rendered into ~/.config/zsh/ai.zsh, which .zshenv sources when is_human
# is false, so humans never load any of it.
#
# Keep it to what an agent cannot tell from the command it knows. An alias
# here must behave like the command it replaces for every flag an agent
# writes (rm -> gomi); anything that changes output or asks for input
# belongs in my.human, where only a human meets it. A setting both sides
# need in different forms is written in both, next to each other in the
# tool's file (BAT_PAGER in bat.nix), not in a shared option one overrides.
{ config, lib, ... }:
let
  inherit (lib) mkOption types;
  cfg = config.my.ai;
  sh = lib.escapeShellArg;
in
{
  options.my.ai = {
    env = mkOption {
      type = types.attrsOf types.str;
      default = { };
      description = "Environment variables exported for agents.";
    };
    aliases = mkOption {
      type = types.attrsOf types.str;
      default = { };
    };
  };

  config.xdg.configFile."zsh/ai.zsh".text = lib.concatLines (
    [ "# Generated by nix/home-manager/ai.nix. Do not edit." ]
    ++ lib.mapAttrsToList (k: v: "export ${k}=${sh v}") cfg.env
    ++ lib.mapAttrsToList (k: v: "alias ${k}=${sh v}") cfg.aliases
  );
}
