# my.env: environment variables every shell gets, AI agents included.
# my.path: directories a tool needs on PATH.
# Both are rendered into ~/.config/zsh/env.zsh, which .zshenv sources
# right after setting PATH and before the is_human branch. Only plain
# variables, so nothing interactive can reach agents. The hand-written
# PATH in .zshenv keeps its global order; my.path only appends to it.
{ config, lib, ... }:
let
  sh = lib.escapeShellArg;
in
{
  options.my = {
    env = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      description = "Variables exported in every zsh, agents included. Values are literal.";
    };
    path = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      description = "Directories appended to PATH in every zsh, each only if it exists.";
    };
  };

  config.xdg.configFile."zsh/env.zsh".text = lib.concatLines (
    [ "# Generated by nix/home-manager/env.nix. Do not edit." ]
    ++ lib.mapAttrsToList (k: v: "export ${k}=${sh v}") config.my.env
    ++ map (d: "if [[ -d ${sh d} ]]; then path+=(${sh d}); fi") config.my.path
  );
}
