# my.human: shell UX for humans only (aliases, plugins, env, snippets).
# Rendered into ~/.config/zsh/human.zsh, which .zshrc sources after the
# `is_human || return 0` guard, so AI agents never see any of it.
{ config, lib, ... }:
let
  inherit (lib) mkOption types;
  cfg = config.my.human;
  sh = lib.escapeShellArg;

  # Plugins in load order: a DAG of their `after`/`before`, sorted by
  # home-manager's topoSort. Plugins with no constraint between them keep
  # topoSort's order (by name). A name that is not a plugin is ignored, so
  # removing a plugin's file never breaks the files that load around it;
  # a cycle fails the build.
  sortedPlugins =
    let
      known = lib.filter (dep: cfg.plugins ? ${dep});
      sorted = lib.hm.dag.topoSort (
        lib.mapAttrs (_: p: lib.hm.dag.entryBetween (known p.before) (known p.after) p) cfg.plugins
      );
    in
    if sorted ? result then
      map (e: e.data) sorted.result
    else
      throw "my.human.plugins: load order has a cycle: ${
        lib.concatMapStringsSep " -> " (e: e.name) sorted.cycle
      }";
in
{
  options.my.human = {
    env = mkOption {
      type = types.attrsOf types.str;
      default = { };
      description = "Environment variables exported for humans.";
    };
    aliases = mkOption {
      type = types.attrsOf types.str;
      default = { };
    };
    globalAliases = mkOption {
      type = types.attrsOf types.str;
      default = { };
    };
    plugins = mkOption {
      default = { };
      description = "zsh plugins to source, keyed by name.";
      type = types.attrsOf (
        types.submodule {
          options = {
            src = mkOption {
              type = types.nullOr types.path;
              default = null;
              description = "Plugin root. null for an init-only entry.";
            };
            file = mkOption {
              type = types.str;
              default = "";
              description = "Path of the file to source, relative to src.";
            };
            preInit = mkOption {
              type = types.lines;
              default = "";
              description = "zsh run before sourcing (e.g. zstyle the plugin reads at load time).";
            };
            init = mkOption {
              type = types.lines;
              default = "";
              description = "zsh run right after sourcing.";
            };
            after = mkOption {
              type = types.listOf types.str;
              default = [ ];
              description = "Plugins (by name) this one is sourced after. Hand-written ~/.zsh/[0-9]*.zsh is `zsh-local`.";
            };
            before = mkOption {
              type = types.listOf types.str;
              default = [ ];
              description = "Plugins (by name) this one is sourced before.";
            };
          };
        }
      );
    };
    init = mkOption {
      type = types.lines;
      default = "";
      description = "Free-form zsh (functions, zstyle, bindkey), after plugins and aliases.";
    };
  };

  config = {
    # Hand-written zsh (bindkeys, setopts, zstyles...) stays editable in the
    # repo. Plugins place themselves around it by this name: zsh-abbr after
    # it, since it binds space in the keymap `bindkey -v` selects, and
    # fast-syntax-highlighting after it, since it defines widgets.
    my.human.plugins.zsh-local = {
      init = ''
        for f in ~/.zsh/[0-9]*.zsh(N); do source "$f"; done
        unset f
      '';
    };

    xdg.configFile."zsh/human.zsh".text = lib.concatLines (
      [ "# Generated by nix/home-manager/human.nix. Do not edit." ]
      ++ lib.mapAttrsToList (k: v: "export ${k}=${sh v}") cfg.env
      ++ lib.concatMap (
        p: [ p.preInit ] ++ lib.optional (p.src != null) "source ${p.src}/${p.file}" ++ [ p.init ]
      ) sortedPlugins
      ++ lib.mapAttrsToList (k: v: "alias ${k}=${sh v}") cfg.aliases
      ++ lib.mapAttrsToList (k: v: "alias -g ${k}=${sh v}") cfg.globalAliases
      ++ [ cfg.init ]
    );
  };
}
