# This is the ov config file.
# Copy it to `$XDG_CONFIG_HOME/ov/config.yaml` or start it with `ov --config ov.yaml`.
#
# QuitSmall: false # Quit if the file size is smaller than the terminal size.
IsWriteOriginal: true # Write the original content when exiting.
# BeforeWriteOriginal: 0 # Write the number of lines before the current location when exiting.
# AfterWriteOriginal: 0 # Write the number of lines after the current location when exiting.
#
# CaseSensitive: false # Case sensitive search.
# SmartCaseSensitive: false # Case sensitive search if the search string contains uppercase characters.
# RegexpSearch: false # Regular expression search.
# Incsearch: true # Incremental search.
#
# MemoryLimit: -1 # The maximum number of lines that can be loaded into memory.
# MemoryLimitFile: 100 # The maximum number of lines that can be loaded into memory when opening a file.
#
# DisableMouse: false # Disable mouse support.
# DisableColumnCycle: false # Disable cycling when moving columns.
#
# ViewMode: markdown # Default view mode.
#
# Debug: false # Debug mode.
#
Prompt:
  Normal:
#    ShowFilename: true # Show the filename.
#    InvertColor: true # Invert the color of the prompt.
#    ProcessOfCount: true # Show the process of count.

# ShrinkChar: '…' # Characters displayed when the column is shrinking.

General:
  TabWidth: 8
  Header: 0
  AlternateRows: false
  ColumnMode: false
  LineNumMode: false
  WrapMode: true
  ColumnDelimiter: ","
  MarkStyleWidth: 1
  # SectionDelimiter: "^#"

# Style
# String of the color name: Foreground, Background, UnderlineColor
# Boolean: Bold, Blink, Dim, Italic, Underline
# Number: UnderlineStyle
StyleAlternate:
  Background: "gray"
StyleHeader:
  Bold: true
StyleOverStrike:
  Bold: true
StyleOverLine:
  Underline: true
StyleLineNumber:
  Bold: true
StyleSearchHighlight:
  Reverse: true
StyleColumnHighlight:
  Reverse: true
StyleMarkLine:
  Background: "darkgoldenrod"
StyleSectionLine:
  Background: "slateblue"
StyleMultiColorHighlight:
  - Foreground: "red"
  - Foreground: "aqua"
  - Foreground: "yellow"
  - Foreground: "fuchsia"
  - Foreground: "lime"
  - Foreground: "blue"
  - Foreground: "grey"
StyleJumpTargetLine:
  Underline: true

# Keybind
# Special key
#   "Enter","Backspace","Tab","Backtab","Esc",
#   "Delete", "Insert",
#   "Up", "Down", "Left", "Right", "Home", "End",
#   "F1...F64"
# Modifier key
#   "ctrl", "alt", "meta", "shift"
# Connect with modifier key + key
#   "ctrl+c"
# If you like less key bindings, copy ov-less.yaml and use it.
# https://raw.githubusercontent.com/noborus/ov/master/ov-less.yaml
KeyBind:
    exit:
        - "Escape"
        - "q"
    cancel:
        - "ctrl+c"
    write_exit:
        - "Q"
    set_write_exit:
        - "ctrl+q"
    suspend:
        - "ctrl+z"
    sync:
        - "ctrl+l"
    reload:
        - "ctrl+alt+l"
        - "F5"
    watch:
        - "ctrl+alt+w"
        - "F4"
    watch_interval:
        - "ctrl+w"
    follow_mode:
        - "ctrl+f"
    follow_all:
        - "ctrl+a"
    follow_section:
        -  "F2"
    help:
        - "h"
        - "ctrl+alt+c"
        - "ctrl+f1"
    logdoc:
        - "ctrl+f2"
        - "ctrl+alt+e"
    down:
        - "Enter"
        - "Down"
        - "ctrl+N"
        - "j"
    up:
        - "Up"
        - "ctrl+p"
        - "k"
    top:
        - "Home"
        - "g"
    bottom:
        - "End"
        - "G"
    left:
        - "left"
    right:
        - "right"
    half_left:
        - "ctrl+left"
    half_right:
        - "ctrl+right"
    page_up:
        - "PageUp"
        - "ctrl+b"
    page_down:
        - "PageDown"
        - "ctrl+v"
    page_half_up:
        - "ctrl+u"
    page_half_down:
        - "ctrl+d"
    section_delimiter:
        - "alt+d"
    section_start:
        - "ctrl+F3"
        - "alt+s"
    section_header_num:
        - "F7"
    hide_other:
        - "alt+-"
    next_section:
        - "space"
    last_section:
        - "9"
    previous_section:
        - "^"
    mark:
        - "m"
    remove_mark:
        - "M"
    remove_all_mark:
        - "ctrl+delete"
    next_mark:
        - ">"
    previous_mark:
        - "<"
    set_view_mode:
        - "p"
        - "P"
    alter_rows_mode:
        - "C"
    line_number_mode:
       - "alt+n"
    search:
        - "/"
    wrap_mode:
        - "w"
        - "W"
    column_mode:
        - "c"
    backsearch:
        - "?"
    delimiter:
        - "d"
    header:
        - "H"
    skip_lines:
        - "ctrl+s"
    tabwidth:
        - "t"
    goto:
        - ":"
    next_search:
        - "n"
    next_backsearch:
        - "N"
    next_doc:
        - "]"
    previous_doc:
        - "["
    toggle_mouse:
        - "ctrl+f3"
        - "ctrl+alt+r"
    multi_color:
        - "."
    jump_target:
        - "alt+j"

Mode:
  markdown:
    SectionDelimiter: "^#"
    WrapMode: true
  psql:
    Header: 2
    AlternateRows: true
    ColumnMode: true
    LineNumMode: false
    WrapMode: true
    ColumnDelimiter: "|"
  mysql:
    Header: 3
    AlternateRows: true
    ColumnMode: true
    LineNumMode: false
    WrapMode: true
    ColumnDelimiter: "|"
