site:
  name: tellme.tokyo
  url: https://tellme.tokyo

editor: nvim
open_command: open -R

hugo:
  command: hugo server --disableFastRender #--buildDrafts
  root_dir: $HOME/src/github.com/babarot/tellme.tokyo
  content_dir: content/post
