#!/bin/bash
#
# @(#) shlib ver.0.1 2015.1.19
#
# Usage:
#   . shlib
# Description:
#   Source all shell script libraris
#
# Copyright (C) 2013-2014 b4b4r07, aka BABAROT
#               <b4b4r07@gmail.com>
#               <https://github.com/b4b4r07>
#
# License:
#   GNU General Public License version 3
#
######################################################################

# Check if exists and sourcing file
import() { eval "[[ -${2:-f} $1 ]]" && source "$1"; }

library_file=(vital.sh *[^vital].sh)
if [[ -n $1 ]]; then
    for ext in "$@"
    do
        if echo *.$ext | grep -qv '*'; then
            library_file+=(*.$ext)
        fi
    done
fi

# source library files
for file in ${library_file[@]}
do
    import "$file"
done
